### 运行主函数

In [3]:
%run main.py --device='cuda' --model='1' --loss='1' --activation='1'

device:cuda:0	model:SinglePerception	optimizer:SGD	loss_function:CrossEntropy	activate_function:Sigmoid
Epoch:0	Train Average Loss:0.15310580640832583	Train Average Accuracy:37.718333333333334%
Train Recall:tensor([0.4829, 0.4767, 0.3770, 0.3763, 0.4314, 0.1653, 0.4441, 0.4444, 0.2849,
        0.2537])
Train Precision:tensor([0.5112, 0.4685, 0.3297, 0.3377, 0.4655, 0.1910, 0.4670, 0.4607, 0.2559,
        0.2687])
Train F1 Score:tensor([0.4966, 0.4726, 0.3518, 0.3559, 0.4478, 0.1772, 0.4553, 0.4524, 0.2697,
        0.2610])
Epoch:0	Test Average Loss:0.07293488830327988	Test Average Accuracy:58.18%
Test Recall:tensor([0.7337, 0.7621, 0.5649, 0.5782, 0.5794, 0.3812, 0.6409, 0.6304, 0.4559,
        0.4480])
Test Precision:tensor([0.7147, 0.7814, 0.5744, 0.5615, 0.5736, 0.3991, 0.6504, 0.6879, 0.3982,
        0.4580])
Test F1 Score:tensor([0.7241, 0.7716, 0.5696, 0.5698, 0.5765, 0.3899, 0.6456, 0.6579, 0.4251,
        0.4529])
模型已保存
Epoch:1	Train Average Loss:0.05880227630188068	Train Avera

KeyboardInterrupt: 

In [ ]:
%run main.py --device='cuda' --model='1' --loss='1' --activation='2'

device:cuda:0	model:SinglePerception	optimizer:SGD	loss_function:CrossEntropy	activate_function:Softmax
Epoch:0	Train Average Loss:0.14951116674741108	Train Average Accuracy:38.44833333333333%
Train Recall:tensor([0.5371, 0.5046, 0.2988, 0.4895, 0.2881, 0.2642, 0.3040, 0.5135, 0.3003,
        0.3054])
Train Precision:tensor([0.4781, 0.5731, 0.3284, 0.4761, 0.3286, 0.2480, 0.3049, 0.5708, 0.2424,
        0.3026])
Train F1 Score:tensor([0.5059, 0.5367, 0.3129, 0.4827, 0.3070, 0.2558, 0.3045, 0.5406, 0.2682,
        0.3040])
Epoch:0	Test Average Loss:0.07386201620101929	Test Average Accuracy:59.8%
Test Recall:tensor([0.7357, 0.7489, 0.5640, 0.6703, 0.5601, 0.4182, 0.5929, 0.6877, 0.4487,
        0.5104])
Test Precision:tensor([0.7232, 0.7907, 0.5803, 0.6381, 0.5607, 0.4776, 0.5850, 0.7229, 0.3871,
        0.5029])
Test F1 Score:tensor([0.7294, 0.7692, 0.5720, 0.6538, 0.5604, 0.4459, 0.5889, 0.7049, 0.4156,
        0.5066])
模型已保存
Epoch:1	Train Average Loss:0.06002645701666673	Train Average

In [ ]:
%run main.py --device='cuda' --model='1' --loss='2' --activation='1'

device:cuda:0	model:SinglePerception	optimizer:SGD	loss_function:MseLoss	activate_function:Sigmoid
Epoch:0	Train Average Loss:0.4181572478055954	Train Average Accuracy:12.085%
Train Recall:tensor([0.1006, 0.2249, 0.1203, 0.1401, 0.1073, 0.1013, 0.0911, 0.0999, 0.0873,
        0.1195])
Train Precision:tensor([0.1307, 0.2266, 0.1202, 0.1266, 0.1125, 0.1035, 0.0983, 0.1032, 0.0740,
        0.1066])
Train F1 Score:tensor([0.1137, 0.2257, 0.1203, 0.1330, 0.1099, 0.1024, 0.0945, 0.1016, 0.0801,
        0.1127])
Epoch:0	Test Average Loss:0.21175964176654816	Test Average Accuracy:13.74%
Test Recall:tensor([0.1429, 0.1991, 0.1444, 0.1614, 0.1120, 0.1401, 0.1232, 0.1070, 0.1201,
        0.1150])
Test Precision:tensor([0.1480, 0.2150, 0.1703, 0.1397, 0.1184, 0.1224, 0.1287, 0.1207, 0.1026,
        0.1112])
Test F1 Score:tensor([0.1454, 0.2068, 0.1563, 0.1497, 0.1151, 0.1307, 0.1259, 0.1135, 0.1107,
        0.1131])
模型已保存
Epoch:1	Train Average Loss:0.17232961059014001	Train Average Accuracy:14.111

In [ ]:
%run main.py --device='cuda' --model='1' --loss='2' --activation='2'

device:cuda:0	model:SinglePerception	optimizer:SGD	loss_function:MseLoss	activate_function:Softmax
Epoch:0	Train Average Loss:0.44135541954040525	Train Average Accuracy:11.156666666666666%
Train Recall:tensor([0.1357, 0.1132, 0.1202, 0.1049, 0.1039, 0.0952, 0.1117, 0.1508, 0.0923,
        0.0839])
Train Precision:tensor([0.1473, 0.1297, 0.1159, 0.1133, 0.1042, 0.0829, 0.0978, 0.1394, 0.1004,
        0.0854])
Train F1 Score:tensor([0.1413, 0.1209, 0.1180, 0.1089, 0.1040, 0.0886, 0.1043, 0.1449, 0.0962,
        0.0846])
Epoch:0	Test Average Loss:0.20748324692249298	Test Average Accuracy:14.6%
Test Recall:tensor([0.1827, 0.1877, 0.1405, 0.1228, 0.1293, 0.1076, 0.1618, 0.1712, 0.1314,
        0.1160])
Test Precision:tensor([0.1868, 0.2109, 0.1430, 0.1303, 0.1224, 0.0895, 0.1429, 0.1765, 0.1306,
        0.1310])
Test F1 Score:tensor([0.1847, 0.1986, 0.1417, 0.1264, 0.1257, 0.0977, 0.1517, 0.1738, 0.1310,
        0.1230])
模型已保存
Epoch:1	Train Average Loss:0.16737760917743047	Train Average Acc

In [ ]:
%run main.py --device='cuda' --model='1' --loss='3' --activation='1'

device:cuda:0	model:SinglePerception	optimizer:SGD	loss_function:AbsLoss	activate_function:Sigmoid
Epoch:0	Train Average Loss:0.15658916038274764	Train Average Accuracy:14.265%
Train Recall:tensor([0.0405, 0.0863, 0.1865, 0.0824, 0.0947, 0.0725, 0.3361, 0.2488, 0.1760,
        0.1004])
Train Precision:tensor([0.0363, 0.1109, 0.1702, 0.0798, 0.1080, 0.0895, 0.2505, 0.3272, 0.1504,
        0.0958])
Train F1 Score:tensor([0.0383, 0.0971, 0.1780, 0.0811, 0.1009, 0.0801, 0.2871, 0.2827, 0.1622,
        0.0980])
Epoch:0	Test Average Loss:0.13516679406166077	Test Average Accuracy:13.85%
Test Recall:tensor([0.0316, 0.1339, 0.1676, 0.1347, 0.0652, 0.0706, 0.3299, 0.1936, 0.1694,
        0.0852])
Test Precision:tensor([0.0403, 0.1470, 0.1866, 0.1222, 0.0687, 0.0675, 0.2287, 0.2494, 0.1364,
        0.0954])
Test F1 Score:tensor([0.0354, 0.1402, 0.1766, 0.1281, 0.0669, 0.0690, 0.2701, 0.2180, 0.1511,
        0.0901])
模型已保存
Epoch:1	Train Average Loss:0.1246427635550499	Train Average Accuracy:14.26%

In [ ]:
%run main.py --device='cuda' --model='1' --loss='3' --activation='2'

device:cuda:0	model:SinglePerception	optimizer:SGD	loss_function:AbsLoss	activate_function:Softmax
Epoch:0	Train Average Loss:0.15076402552922566	Train Average Accuracy:8.756666666666666%
Train Recall:tensor([0.0927, 0.1424, 0.1788, 0.0347, 0.0512, 0.0917, 0.0145, 0.1315, 0.0590,
        0.0699])
Train Precision:tensor([0.0787, 0.2003, 0.2276, 0.0190, 0.0910, 0.0666, 0.0214, 0.1374, 0.0633,
        0.0681])
Train F1 Score:tensor([0.0851, 0.1664, 0.2002, 0.0245, 0.0655, 0.0772, 0.0173, 0.1344, 0.0611,
        0.0690])
Epoch:0	Test Average Loss:0.1309283971786499	Test Average Accuracy:9.31%
Test Recall:tensor([0.1173, 0.1207, 0.1899, 0.0347, 0.0672, 0.1099, 0.0240, 0.1294, 0.0749,
        0.0545])
Test Precision:tensor([0.0903, 0.1805, 0.2276, 0.0213, 0.0866, 0.0743, 0.0381, 0.1444, 0.0793,
        0.0589])
Test F1 Score:tensor([0.1020, 0.1447, 0.2071, 0.0264, 0.0757, 0.0886, 0.0295, 0.1365, 0.0770,
        0.0566])
模型已保存
Epoch:1	Train Average Loss:0.11947893892129262	Train Average Accur

In [ ]:
%run main.py --device='cuda' --model='2' --loss='1' --activation='1'

device:cuda:0	model:MultiPerception1	optimizer:SGD	loss_function:CrossEntropy	activate_function:Sigmoid
Epoch:0	Train Average Loss:0.07170287303527197	Train Average Accuracy:12.1%
Train Recall:tensor([3.7819e-02, 8.3180e-01, 5.5556e-02, 4.6159e-02, 6.8470e-04, 0.0000e+00,
        1.5377e-02, 8.2522e-02, 3.4524e-02, 0.0000e+00])
Train Precision:tensor([0.1213, 0.1209, 0.1072, 0.1486, 0.4000,    nan, 0.1850, 0.1276, 0.0908,
           nan])
Train F1 Score:tensor([0.0577, 0.2111, 0.0732, 0.0704, 0.0014,    nan, 0.0284, 0.1002, 0.0500,
           nan])
Epoch:0	Test Average Loss:0.07142440974712372	Test Average Accuracy:11.35%
Test Recall:tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])
Test Precision:tensor([   nan, 0.1135,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan])
Test F1 Score:tensor([   nan, 0.2039,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan])
模型已保存
Epoch:1	Train Average Loss:0.0706584945400556	Train Average Accuracy:21.56833333

In [8]:
%run main.py --device='cuda' --model='2' --loss='1' --activation='2'

device:cuda:0	model:MultiPerception1	optimizer:SGD	loss_function:CrossEntropy	activate_function:Softmax
Epoch:0	Train Average Loss:0.07195503000020981	Train Average Accuracy:10.773333333333333%
Train Recall:tensor([0.0000, 0.2931, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7164, 0.0000,
        0.0000])
Train Precision:tensor([   nan, 0.1146,    nan,    nan,    nan,    nan,    nan, 0.1050,    nan,
           nan])
Train F1 Score:tensor([   nan, 0.1647,    nan,    nan,    nan,    nan,    nan, 0.1831,    nan,
           nan])
Epoch:0	Test Average Loss:0.07202468067407608	Test Average Accuracy:11.35%
Test Recall:tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])
Test Precision:tensor([   nan, 0.1135,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan])
Test F1 Score:tensor([   nan, 0.2039,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan])
模型已保存
Epoch:1	Train Average Loss:0.07191541642745336	Train Average Accuracy:11.236666666666666%
Train Recall:ten

In [ ]:
%run main.py --device='cuda' --model='2' --loss='1' --activation='3'

device:cuda:0	model:MultiPerception1	optimizer:SGD	loss_function:CrossEntropy	activate_function:Relu
Epoch:0	Train Average Loss:0.03472322360376517	Train Average Accuracy:72.14333333333333%
Train Recall:tensor([0.8482, 0.9201, 0.6809, 0.7261, 0.6486, 0.3798, 0.8472, 0.6675, 0.7741,
        0.6685])
Train Precision:tensor([0.8825, 0.6479, 0.7875, 0.7004, 0.8357, 0.7913, 0.7854, 0.8714, 0.4973,
        0.6859])
Train F1 Score:tensor([0.8650, 0.7604, 0.7303, 0.7131, 0.7303, 0.5133, 0.8152, 0.7560, 0.6055,
        0.6771])
Epoch:0	Test Average Loss:0.01322212629020214	Test Average Accuracy:88.32%
Test Recall:tensor([0.9663, 0.9648, 0.8614, 0.8782, 0.9114, 0.7713, 0.9395, 0.8726, 0.8029,
        0.8444])
Test Precision:tensor([0.9348, 0.9351, 0.9016, 0.8808, 0.8723, 0.8142, 0.8687, 0.9070, 0.8427,
        0.8529])
Test F1 Score:tensor([0.9503, 0.9497, 0.8811, 0.8795, 0.8914, 0.7922, 0.9027, 0.8894, 0.8223,
        0.8486])
模型已保存
Epoch:1	Train Average Loss:0.011605420389771462	Train Average 

In [ ]:
%run main.py --device='cuda' --model='2' --loss='1' --activation='4'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='1' --activation='5'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='1' --activation='6'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='1' --activation='7'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='2' --activation='1'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='2' --activation='2'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='2' --activation='3'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='2' --activation='4'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='2' --activation='5'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='2' --activation='6'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='2' --activation='7'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='3' --activation='1'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='3' --activation='2'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='3' --activation='3'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='3' --activation='4'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='3' --activation='5'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='3' --activation='6'

In [ ]:
%run main.py --device='cuda' --model='2' --loss='3' --activation='7'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='1' --activation='1'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='1' --activation='2'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='1' --activation='3'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='1' --activation='4'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='1' --activation='5'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='1' --activation='6'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='1' --activation='7'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='2' --activation='1'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='2' --activation='2'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='2' --activation='3'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='2' --activation='4'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='2' --activation='5'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='2' --activation='6'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='2' --activation='7'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='3' --activation='1'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='3' --activation='2'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='3' --activation='3'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='3' --activation='4'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='3' --activation='5'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='3' --activation='6'

In [ ]:
%run main.py --device='cuda' --model='3' --loss='3' --activation='7'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='1' --activation='1'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='1' --activation='2'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='1' --activation='3'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='1' --activation='4'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='1' --activation='5'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='1' --activation='6'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='1' --activation='7'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='2' --activation='1'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='2' --activation='2'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='2' --activation='3'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='2' --activation='4'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='2' --activation='5'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='2' --activation='6'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='2' --activation='7'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='3' --activation='1'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='3' --activation='2'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='3' --activation='3'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='3' --activation='4'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='3' --activation='5'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='3' --activation='6'

In [ ]:
%run main.py --device='cuda' --model='4' --loss='3' --activation='7'

In [1]:
%run main.py --h

usage: main.py [-h] [--data_dir DATA_DIR] [--batch_size BATCH_SIZE]
               [--learning_rate LEARNING_RATE] [--epochs EPOCHS]
               [--optimizer OPTIMIZER] --model {1,2,3,4} --loss {1,2,3}
               [--device DEVICE] --activation {1,2,3,4,5,6,7}

Pytorch MNIST Example

optional arguments:
  -h, --help            show this help message and exit
  --data_dir DATA_DIR   Path to dataset
  --batch_size BATCH_SIZE
                        Batch size
  --learning_rate LEARNING_RATE
                        Learning rate
  --epochs EPOCHS       Number of Epoch
  --optimizer OPTIMIZER
                        Optimizer to use
  --model {1,2,3,4}     1 for SinglePerception, 2 for MLP1, 3 for MLP2, 4 for
                        MLP3
  --loss {1,2,3}        Loss function to use, 1 for CrossEntropy, 2 for
                        MseLoss, 3 for AbsLoss
  --device DEVICE       Device to use
  --activation {1,2,3,4,5,6,7}
                        Activation function to use, 1 for Sigm

In [3]:
from sklearn.metrics import confusion_matrix  
import numpy as np  
  
# 假设你有以下真实标签和预测标签  
y_true = [0, 1, 1, 1, 0, 1, 2, 1, 0, 1]  # 真实标签，0和1代表两个不同的类别  
y_pred = [0, 0, 2, 1, 2, 1, 1, 1, 0, 1]  # 模型预测的标签  
  
# 使用confusion_matrix函数计算混淆矩阵  
cm = confusion_matrix(y_true, y_pred)  
  
# 输出混淆矩阵  
print("Confusion Matrix:")  
print(cm)

Confusion Matrix:
[[2 0 1]
 [1 4 1]
 [0 1 0]]


In [6]:
import torch  
  
# 假设你有以下tensor形式的真实标签和预测标签  
y_true = torch.tensor([0, 1, 2, 0, 1, 2, 0, 1, 2])  # 真实标签的tensor  
y_pred = torch.tensor([0, 2, 1, 0, 0, 1, 2, 2, 2])  # 模型预测的标签的tensor  
  
# 在PyTorch中，你可以使用自定义函数来生成混淆矩阵  
def confusion_matrix(y_true, y_pred, num_classes):  
    # 初始化混淆矩阵  
    cm = torch.zeros(num_classes, num_classes)  
      
    # 遍历标签  
    for t, p in zip(y_true, y_pred):  
        # 增加对应位置的计数  
        cm[t, p] += 1  
      
    return cm  
  
# 获取类别数量  
num_classes = int(torch.max(y_true).item() + 1)  
  
# 生成混淆矩阵  
cm = confusion_matrix(y_true, y_pred, num_classes)  
  
# 将tensor转换为NumPy数组以便打印和查看  
cm_numpy = cm.numpy()  
  
# 输出混淆矩阵  
print("Confusion Matrix:")  
print(cm_numpy)

Confusion Matrix:
[[2. 0. 1.]
 [1. 0. 2.]
 [0. 2. 1.]]
